//// src/dilemas.js
//// Lista de dilemas iniciais, já formatada como um array de objetos.
//
//export const dilemasIniciais = [
//  { titulo: "Provérbio do Dia", mensagem: "Água mole em pedra dura, tanto bate até que fura." },
//  { titulo: "Provérbio do Dia", mensagem: "Antes tarde do que nunca." },
//  { titulo: "Provérbio do Dia", mensagem: "Casa de ferreiro, espeto de pau." },
//  { titulo: "Provérbio do Dia", mensagem: "De grão em grão, a galinha enche o papo." },
//  { titulo: "Provérbio do Dia", mensagem: "Deus ajuda quem cedo madruga." },
//  { titulo: "Provérbio do Dia", mensagem: "Diz-me com quem andas e te direi quem és." },
//  { titulo: "Provérbio do Dia", mensagem: "Em time que está ganhando não se mexe." },
//  { titulo: "Provérbio do Dia", mensagem: "Errar é humano, persistir no erro é burrice." },
//  { titulo: "Provérbio do Dia", mensagem: "Filho de peixe, peixinho é." },
//  { titulo: "Provérbio do Dia", mensagem: "Gato escaldado tem medo de água fria." },
//  { titulo: "Provérbio do Dia", mensagem: "Ladrão que rouba ladrão tem cem anos de perdão." },
//  { titulo: "Provérbio do Dia", mensagem: "Mais vale um pássaro na mão do que dois voando." },
//  { titulo: "Provérbio do Dia", mensagem: "Mente vazia, oficina do diabo." },
//  { titulo: "Provérbio do Dia", mensagem: "Não adianta chorar sobre o leite derramado." },
//  { titulo: "Provérbio do Dia", mensagem: "Não deixe para amanhã o que você pode fazer hoje." },
//  { titulo: "Provérbio do Dia", mensagem: "O barato sai caro." },
//  { titulo: "Provérbio do Dia", mensagem: "O combinado não sai caro." },
//  { titulo: "Provérbio do Dia", mensagem: "O seguro morreu de velho." },
//  { titulo: "Provérbio do Dia", mensagem: "Pau que nasce torto, nunca se endireita." },
//  { titulo: "Provérbio do Dia", mensagem: "Para bom entendedor, meia palavra basta." },
//  { titulo: "Provérbio do Dia", mensagem: "Quem ama o feio, bonito lhe parece." },
//  { titulo: "Provérbio do Dia", mensagem: "Quem canta seus males espanta." },
//  { titulo: "Provérbio do Dia", mensagem: "Quem com ferro fere, com ferro será ferido." },
//  { titulo: "Provérbio do Dia", mensagem: "Quem não tem cão, caça com gato." },
//  { titulo: "Provérbio do Dia", mensagem: "Quem ri por último, ri melhor." },
//  { titulo: "Provérbio do Dia", mensagem: "Quem semeia vento, colhe tempestade." },
//  { titulo: "Provérbio do Dia", mensagem: "Saco vazio não para em pé." },
//  { titulo: "Provérbio do Dia", mensagem: "Segunda-feira, dia de preguiça." },
//  { titulo: "Provérbio do Dia", mensagem: "Tempo é dinheiro." },
//  { titulo: "Provérbio do Dia", mensagem: "Um dia é da caça, outro do caçador." },
//  { titulo: "Provérbio do Dia", mensagem: "Quando um não quer, dois não brigam." }
//];
